# GitHub Actions for AudioKit Cookbook
name: CI

on: [push, pull_request]
env:
  XCODE_VER: 14.2

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['14.2']
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out AudioKit Cookbook
        uses: actions/checkout@v2
      - name: Build AudioKit Cookbook
        run: |
          set -euo pipefail
          xcodebuild -project Cookbook/Cookbook.xcodeproj -sdk iphonesimulator -scheme Cookbook -arch x86_64 ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build | xcpretty -c

  # Send notification to Discord on failure.
  send_notification:
    name: Send Notification
    uses: AudioKit/ci/.github/workflows/send_notification.yml@main
    needs: [build]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    secrets: inherit
